name: learn-github-actions
on: [push, workflow_dispatch]
jobs:
  DEV:
    runs-on: ubuntu-latest
    steps:
      - run: echo HELLO

  QA:
    runs-on: ubuntu-latest
    needs:
      - DEV
    steps:
      - run: echo HELLO

  UAT:
    runs-on: ubuntu-latest
    needs:
      - QA
    steps:
      - run: echo HELLO

  PROD:
    runs-on: ubuntu-latest
    needs:
      - UAT
    steps:
      - run: echo HELLO